services:
  node:
    container_name: node
    image: node:22.13.1-alpine3.21
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/src
    working_dir: /var/www/src
    tty: true
    user: "1000:1000"